# Generated by Django 6.0.1 on 2026-01-17 14:47

import appointments.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('specialty', models.CharField(choices=[('DERMATOLOGIST', 'Dermatologist'), ('ALLERGIST', 'Allergist'), ('SURGEON', 'Plastic Surgeon'), ('GP', 'General Practitioner'), ('ONCOLOGIST', 'Oncologist')], db_index=True, max_length=50)),
                ('hospital_name', models.CharField(max_length=100)),
                ('city', models.CharField(db_index=True, max_length=50)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('qualification', models.CharField(help_text='e.g., MBBS, FCPS', max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['specialty', 'city'], name='appointment_special_bf9861_idx'), models.Index(fields=['specialty', 'is_available'], name='appointment_special_89a7b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('symptoms', appointments.fields.EncryptedTextField(blank=True)),
                ('ai_diagnosis', appointments.fields.EncryptedTextField(blank=True)),
                ('doctor_notes', appointments.fields.EncryptedTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.doctor')),
            ],
            options={
                'ordering': ['-date_time'],
                'indexes': [models.Index(fields=['doctor', 'date_time'], name='appointment_doctor__1c115c_idx'), models.Index(fields=['patient', 'date_time'], name='appointment_patient_bce84f_idx')],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'date_time'), name='unique_doctor_appointment_time')],
            },
        ),
    ]
