# Generated by Django 6.0.1 on 2026-01-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinlesionscan',
            name='heatmap_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
